name             'hyper-opsworks'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures hyper-opsworks'
long_description 'Installs/Configures hyper-opsworks'
version          '0.1.0'
